{{ if .Values.environment eq "local" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.access.key }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.access.secret }}
{{ end}}
